### ISSUE TITLE
戦闘bgmをつける

### ISSUE THREAD

**Issue by peta345** [FreeParty/rpg2d#13]
# 作業量(大)

# todo
[] いたるところのseや、フィールドの音楽をつける

# way
soundの仕組みはつでに作成済み

**Comment by Murakami0105** [comment]
dendai2_1でBGMの試作をします

**Comment by Murakami0105** [comment]
敵リストのtypeをこのシステムに合わせる
(逃げれない雑魚：１，ボス：2，ラスボス：3)
それに伴い，仮で当ててた区分1のBGMを雑魚戦BGMに戻す
