### ISSUE TITLE
npcをつくる

### ISSUE THREAD

**Issue by peta345** [FreeParty/rpg2d#19]
優先度(中)
# todo
[] npc をつくる
[] 会話テキストも

**Comment by Murakami0105** [comment]
第一ステップ：npcフォルダ内の画像をスライス
第二ステップ：テキストファイルを書きつつNPCを設置
第三ステップ：(敵が確定したら)ボスを含むシンボルエネミーを配置

**Comment by Murakami0105** [comment]
残りはボスのみ
