### ISSUE TITLE
デバッグ用のアイテム、設定等を戻す

### ISSUE THREAD

**Issue by FlyBird-JP** [FreeParty/rpg2d#200]
・map_staitionの通行許可証

**Comment by FlyBird-JP** [comment]
・map_dendai_restの学生証

**Comment by FlyBird-JP** [comment]
・map_dendai2_1のエレベーターのカギ

**Comment by FlyBird-JP** [comment]
・EncountControllerを有効にすべきシーンでは有効にする

**Comment by FlyBird-JP** [comment]
・エンドロールのクレジット（すこし加筆しました。何かあったらどんどん書き換えてください）

**Comment by FlyBird-JP** [comment]
・プレイヤーの初期値

**Comment by Murakami0105** [comment]
上に上がってる項目は修正したはずなので閉じます

もし何か加筆するならまた開けてください
