### ISSUE TITLE
masterでnoenterレイヤーの当たり判定がきかなくなる

### ISSUE THREAD

**Issue by peta345** [FreeParty/rpg2d#32]
# way
noenter tile map collider2d コンポーネントのuse commposite をfalseにして修正

**Comment by peta345** [comment]
上を実行したらpc上のエミュ上ではうまく効いたが、実機テストをすると効かなくなった
もう一度pc上のエミュでuse composite をtrueにしたら実機テストでも当たり判定がきいた
どういうことなの..

**Comment by FlyBird-JP** [comment]
Unity 2017.2.0f3で解決？
